dist: trusty

language: php

php:
  - 7.2

addons:
  postgresql: "9.5"

services:
  - redis-server

before_script:
  - cp .env.travis .env
  - psql -c 'create database catalex_users_test;' -U postgres
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit